[package]
name = "rustwebserver"
version = "0.1.0"
edition = "2021"

[lib]
name = "utils"
path = "src/lib.rs"

[[bin]]
name = "rustwebserver"
path = "src/main.rs"

[dependencies]
actix-web = "4.0.1"
actix-rt = "2.7.0"